CREATE TABLE `TurnosCaja` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `turno_abierto` tinyint(1) NOT NULL DEFAULT '1',
  `turno_abierto_en` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `turno_cerrado_en` timestamp NULL DEFAULT NULL,
  `usuario_id` int(11) NOT NULL,
  `monto_inicial` decimal(10,2) NOT NULL DEFAULT '0.00',
  `monto_final` decimal(10,2) NOT NULL DEFAULT '0.00',
  `total_ventas` decimal(10,2) NOT NULL DEFAULT '0.00',
  `total_contado` decimal(10,2) NOT NULL DEFAULT '0.00',
  `total_tarjeta` decimal(10,2) NOT NULL DEFAULT '0.00',
  `total_transferencia` decimal(10,2) NOT NULL DEFAULT '0.00',
  `total_cheque` decimal(10,2) NOT NULL DEFAULT '0.00',
  `total_credito` decimal(10,2) NOT NULL DEFAULT '0.00',
  `total_uber_eats` decimal(10,2) NOT NULL DEFAULT '0.00',
  `total_otros_medios` decimal(10,2) NOT NULL DEFAULT '0.00',
  `total_general` decimal(10,2) NOT NULL DEFAULT '0.00',
  `diferencia_general` decimal(10,2) NOT NULL DEFAULT '0.00',
  `observaciones` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_turno_estado` (`turno_abierto`),
  KEY `idx_usuario` (`usuario_id`),
  KEY `idx_fecha_apertura` (`turno_abierto_en`),
  KEY `idx_fecha_cierre` (`turno_cerrado_en`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;